#!/usr/bin/env bash

LDAP_URI="ldap://127.0.0.1:30389"
BASE_DN="dc=petra,dc=ac,dc=id"
PEOPLE_BASE="ou=people,${BASE_DN}"
ROLE_GROUP_BASE="ou=roles,ou=groups,${BASE_DN}"

BIND_DN="cn=admin,${BASE_DN}"
BIND_PW_FILE="/opt/petra_iam_big_project/.secrets/ldap_admin_password.txt"

# Attribute member di role group.
# Kalau group kamu pakai uniqueMember, ganti jadi uniqueMember.
GROUP_MEMBER_ATTR="member"

# Mapping role LDAP group -> affiliation value
ROLE_GROUP_PREFIX="role-"

# Role yang diizinkan
ALLOWED_AFFILIATIONS=("student" "staff" "alumni" "external")

# Prioritas primary kalau sync dari banyak role
# Edit sesuai kebutuhan institusi
AFFILIATION_PRIORITY=("staff" "student" "alumni" "external")

# Kalau true, bulk exact sync akan menghapus role-group lain yang tidak ada di desired roles
EXACT_GROUP_SYNC="true"

# Kalau true, script validate --fix akan mencoba repair otomatis
AUTO_FIX_DEFAULT="false"